### ISSUE TITLE
All timerfd-root-test failed on macOS

### ISSUE THREAD

**Issue by Torrekie** [jiixyj/epoll-shim#37] opened 2022-06-20 09:26 UTC
On macos branch
```
The following tests FAILED:
        123 - timerfd-root-test.timerfd_root__zero_read_on_abs_realtime (Failed)
        124 - timerfd-root-test.timerfd_root__read_on_abs_realtime_no_interval (Failed)
        125 - timerfd-root-test.timerfd_root__cancel_on_set (Failed)
        126 - timerfd-root-test.timerfd_root__cancel_on_set_init (Failed)
        127 - timerfd-root-test.timerfd_root__clock_change_notification (Failed)
        128 - timerfd-root-test.timerfd_root__advance_time_no_cancel (Failed)
        129 - timerfd-root-test-interpose.timerfd_root__zero_read_on_abs_realtime (Failed)
        130 - timerfd-root-test-interpose.timerfd_root__read_on_abs_realtime_no_interval (Failed)
        131 - timerfd-root-test-interpose.timerfd_root__cancel_on_set (Failed)
        132 - timerfd-root-test-interpose.timerfd_root__cancel_on_set_init (Failed)
        133 - timerfd-root-test-interpose.timerfd_root__clock_change_notification (Failed)
        134 - timerfd-root-test-interpose.timerfd_root__advance_time_no_cancel (Failed)
Errors while running CTest
```
 They actually passed the tests, marked as failed because file descriptors leaks (or they haven't been closed after tests).

**Comment by jiixyj** [comment] 2022-07-11 20:06
Thanks for the report! Should be fixed in 56f35ede0a14b5206ced8d01c84203bbea257314.

The cause of the failing leak check was ASL. On macOS, `settimeofday` connects to ASL (a logging service), opening a socket that stays open.

**Closed by jiixyj** 2022-07-11 20:06 UTC
